version: "3.7"

services:
    web:
        container_name: web
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - fnsc.dev
        depends_on:
            - mysql
            - nginx

    nginx:
        container_name: nginx
        image: nginx:1.21.6
        working_dir: /var/www/html
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx_app.conf:/etc/nginx/conf.d/nginx_app.conf
        networks:
            - fnsc.dev

    mysql:
        container_name: mysql
        image: mysql:8
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: ${DB_SERVICE_TAG}
            SERVICE_NAME: ${DB_CONNECTION}
        networks:
            - fnsc.dev

    assets:
        container_name: assets
        image: node:lts
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - fnsc.dev

networks:
    fnsc.dev:
        driver: bridge
